(() => {
  'use strict';
  const DB='earth-observe-offline', STORE='state', DB_VERSION=1, DAY=86400000;
  const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let events=[], filter='all', selected=null, countryFeatures=[], rotLon=-139.7*Math.PI/180, rotLat=35.7*Math.PI/180, dragging=false, lastPointer=null, pointerStart=null, db=null, memState={}, toastTimer;

  const store={
    async open(){if(!('indexedDB'in window))return;try{db=await new Promise((resolve,reject)=>{const req=indexedDB.open(DB,DB_VERSION);req.onupgradeneeded=()=>req.result.createObjectStore(STORE);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}catch{db=null}},
    async get(key){if(db)try{return await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly'),req=tx.objectStore(STORE).get(key);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}catch{}try{return JSON.parse(localStorage.getItem(DB+':'+key)||'null')}catch{return memState[key]}},
    async set(key,value){memState[key]=value;if(db)try{await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(value,key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});return}catch{}try{localStorage.setItem(DB+':'+key,JSON.stringify(value))}catch{}}
  };
  function toast(message){const el=$('toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2600)}
  function jst(value){if(!value)return NaN;if(typeof value==='number')return value;const s=String(value);return Date.parse(/[zZ]|[+-]\d{2}:?\d{2}$/.test(s)?s:s.replace(/^([0-9]{4})\/([0-9]{2})\/([0-9]{2})\s/,'$1-$2-$3T')+'+09:00')}
  function fmtDate(t){return new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(t)}
  function age(t){const m=Math.max(0,Math.floor((Date.now()-t)/60000));return m<1?'たった今':m<60?`${m}分前`:m<1440?`${Math.floor(m/60)}時間前`:`${Math.floor(m/1440)}日前`}
  function isJapan(e){if(e.countryCode==='JP')return true;if(e.lat==null||e.lon==null)return false;return e.lat>=20&&e.lat<=46&&e.lon>=122&&e.lon<=154}
  function kindName(k){return({quake:'地震',tsunami:'津波',storm:'気象',other:'その他'})[k]||'その他'}
  function icon(e){return e.kind==='quake'?'⌁':e.kind==='tsunami'?'≋':e.kind==='storm'?(e.hazardType==='TC'?'🌀':'☁'):'✳'}
  function signature(e){return `${e.id}|${e.time}|${e.place}|${e.intensity||''}`}
  function setStatus(text,online){$('statusText').textContent=text;$('statusDot').style.background=online?'var(--green)':'var(--amber)'}
  function tick(){$('clock').textContent=new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date())}
  function visible(){return events.filter(e=>(filter==='all'||filter==='japan'&&isJapan(e)||filter===e.kind)&&Number.isFinite(Number(e.lat))&&Number.isFinite(Number(e.lon)))}
  function persist(){store.set('events',events);store.set('savedAt',Date.now());$('savedAt').textContent=new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date())+' 東京'}
  function render(){const list=visible().sort((a,b)=>(Number(b.time)||0)-(Number(a.time)||0)), el=$('eventList');$('eventCount').textContent=`${list.length}件`;$('empty').classList.toggle('hidden',list.length>0);el.innerHTML=list.map(e=>`<article class="event-row ${selected===e.id?'active':''}" data-id="${esc(e.id)}"><span class="event-icon ${esc(e.kind)}">${icon(e)}</span><div class="event-main"><div class="event-place">${esc(e.place||'発生地点')}</div><div class="event-meta">${kindName(e.kind)} · ${esc(e.source||'保存データ')}${e.depth!=null&&Number(e.depth)>=0?` · 深さ${esc(e.depth)}km`:''}${e.eew?' · 緊急地震速報':''}</div></div><div class="event-side"><b>${esc(e.intensity|| (e.mag?`M${Number(e.mag).toFixed(1)}`:''))}</b>${age(Number(e.time)||Date.now())}</div></article>`).join('');el.querySelectorAll('.event-row').forEach(row=>row.addEventListener('click',()=>selectEvent(row.dataset.id)));draw()}
  function selectEvent(id){selected=id;const e=events.find(x=>String(x.id)===String(id));const box=$('selected');if(!e){box.classList.add('hidden')}else{box.innerHTML=`<strong>${esc(e.place||'発生地点')}</strong><br>${kindName(e.kind)} · ${esc(e.intensity|| (e.mag?`M${Number(e.mag).toFixed(1)}`:'情報'))} · ${fmtDate(Number(e.time)||Date.now())}<br><span class="coords">${Number(e.lat).toFixed(2)}°, ${Number(e.lon).toFixed(2)}°${e.source?' · '+esc(e.source):''}</span>`;box.classList.remove('hidden');rotLon=-Number(e.lon)*Math.PI/180;rotLat=Number(e.lat)*Math.PI/180}render()}
  function color(e){return e.kind==='quake'?'#ff7182':e.kind==='tsunami'?'#62b7ff':e.kind==='storm'?'#ffbd69':'#c7a0ff'}
  function draw(){const canvas=$('globe'),ctx=canvas.getContext('2d'),rect=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2),w=Math.max(1,rect.width),h=Math.max(1,rect.height);if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr)}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const radius=Math.min(w,h)*.44,cx=w/2,cy=h/2;const grad=ctx.createRadialGradient(cx-radius*.3,cy-radius*.35,radius*.06,cx,cy,radius);grad.addColorStop(0,'#12344a');grad.addColorStop(1,'#081522');ctx.fillStyle=grad;ctx.beginPath();ctx.arc(cx,cy,radius,0,Math.PI*2);ctx.fill();ctx.save();ctx.beginPath();ctx.arc(cx,cy,radius,0,Math.PI*2);ctx.clip();
    const project=(lon,lat)=>{const p=lat*Math.PI/180,l=lon*Math.PI/180-rotLon,cp=Math.cos(p),z=Math.sin(p)*Math.cos(rotLat)+cp*Math.cos(l)*Math.sin(rotLat);return{x:cx+radius*cp*Math.sin(l),y:cy-radius*(Math.sin(p)*Math.cos(rotLat)-cp*Math.cos(l)*Math.sin(rotLat)),z}};
    ctx.strokeStyle='#3d7080';ctx.globalAlpha=.45;ctx.lineWidth=.65;for(let lat=-60;lat<=60;lat+=30){ctx.beginPath();let active=false;for(let lon=-180;lon<=180;lon+=3){const q=project(lon,lat);if(q.z>0){if(!active){ctx.moveTo(q.x,q.y);active=true}else ctx.lineTo(q.x,q.y)}else active=false}ctx.stroke()}for(let lon=-150;lon<=180;lon+=30){ctx.beginPath();let active=false;for(let lat=-88;lat<=88;lat+=3){const q=project(lon,lat);if(q.z>0){if(!active){ctx.moveTo(q.x,q.y);active=true}else ctx.lineTo(q.x,q.y)}else active=false}ctx.stroke()}
    ctx.globalAlpha=1;ctx.fillStyle='#174238';ctx.strokeStyle='#367767';ctx.lineWidth=.45;const pathRing=ring=>{ctx.beginPath();let open=false;for(const pair of ring){const q=project(pair[0],pair[1]);if(q.z>0){if(!open){ctx.moveTo(q.x,q.y);open=true}else ctx.lineTo(q.x,q.y)}else open=false}ctx.closePath();ctx.fill();ctx.stroke()};for(const feature of countryFeatures){const g=feature.geometry;if(!g)continue;const polys=g.type==='Polygon'?[g.coordinates]:g.type==='MultiPolygon'?g.coordinates:[];for(const poly of polys)if(poly[0])pathRing(poly[0])}
    const geoDest=(lat,lon,distance,bearing)=>{const R=6371,δ=distance/R,φ=lat*Math.PI/180,λ=lon*Math.PI/180,θ=bearing,φ2=Math.asin(Math.sin(φ)*Math.cos(δ)+Math.cos(φ)*Math.sin(δ)*Math.cos(θ)),λ2=λ+Math.atan2(Math.sin(θ)*Math.sin(δ)*Math.cos(φ),Math.cos(δ)-Math.sin(φ)*Math.sin(φ2));return[φ2*180/Math.PI,((λ2*180/Math.PI+540)%360)-180]};
    for(const e of visible()){if(e.kind!=='quake')continue;const ageSec=(Date.now()-Number(e.time))/1000;if(ageSec<0||ageSec>=900)continue;for(const [speed,stroke] of [[6,'#62b7ffbd'],[3.5,'#ffbd69bd']]){const km=speed*ageSec;if(km<1)continue;ctx.beginPath();let started=false;for(let i=0;i<=96;i++){const [lat,lon]=geoDest(Number(e.lat),Number(e.lon),km,i*Math.PI*2/96),q=project(lon,lat);if(q.z>0){if(!started){ctx.moveTo(q.x,q.y);started=true}else ctx.lineTo(q.x,q.y)}else started=false}ctx.strokeStyle=stroke;ctx.lineWidth=1.25;ctx.stroke()}}
    const pins=[];for(const e of visible()){const q=project(Number(e.lon),Number(e.lat));if(q.z>0)pins.push({e,...q})}pins.sort((a,b)=>a.z-b.z);for(const p of pins){const r=p.e.id===selected?5.5:3.4;ctx.beginPath();ctx.fillStyle=color(p.e);ctx.globalAlpha=.24;ctx.arc(p.x,p.y,r+4,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;ctx.beginPath();ctx.fillStyle=color(p.e);ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#07111d';ctx.lineWidth=1.4;ctx.stroke()}ctx.restore();ctx.strokeStyle='#5ce1cb';ctx.globalAlpha=.5;ctx.lineWidth=1;ctx.beginPath();ctx.arc(cx,cy,radius,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1}
  function eventFromP2P(item){const q=item.earthquake||{},h=q.hypocenter||{};if(h.latitude==null||h.longitude==null||!Number.isFinite(Number(h.latitude))||Number(h.latitude)===-200||!Number.isFinite(Number(h.longitude))||Number(h.longitude)===-200)return null;const t=jst(q.originTime||q.time)||jst(item.issue?.time||item.time)||Date.now(),code=Number(item.code),scales=(item.areas||[]).map(a=>Number(a.scaleTo)).filter(n=>Number.isFinite(n)&&n>=0),issueId=item.issue?.eventId||`${Math.round(t)}-${Number(h.latitude).toFixed(1)}-${Number(h.longitude).toFixed(1)}`;return{id:`p2p-${issueId}`,kind:'quake',place:h.name||'日本付近',lat:Number(h.latitude),lon:Number(h.longitude),countryCode:'JP',time:t,mag:Number(q.magnitude)>=0?Number(q.magnitude):null,depth:Number(q.depth)>=0?Number(q.depth):null,intensity:code===556?(scales.length?`予測震度${Math.max(...scales)/10}`:'緊急地震速報'):Number(q.maxScale)>=0?`最大震度${q.maxScale/10}`:'',eew:code===556,source:'P2P / 気象庁'}}
  const tsunamiCoords={'北海道太平洋沿岸東部':[42.5,144.5],'北海道太平洋沿岸西部':[42,142],'青森県太平洋沿岸':[40.8,142.1],'岩手県':[39.7,142],'宮城県':[38.3,142],'福島県':[37.3,141.2],'茨城県':[36.4,141],'千葉県九十九里・外房':[35.2,141],'伊豆諸島':[33,139.5],'小笠原諸島':[27,142],'相模湾・三浦半島':[35.1,139.4],'静岡県':[34.7,138.5],'愛知県外海':[34.6,137.2],'三重県南部':[33.9,136.2],'和歌山県':[33.7,135.5],'徳島県':[33.7,134.7],'高知県':[33.2,133.5],'宮崎県':[31.8,131.5],'鹿児島県東部':[31.2,131],'沖縄本島地方':[26.2,127.7]};
  function eventFromTsunami(item){const gradeMap={MajorWarning:'大津波警報',Warning:'津波警報',Watch:'津波注意報',Unknown:'津波情報'},when=jst(item.issue?.time||item.time)||Date.now();return(item.areas||[]).map((a,i)=>{const name=a.name||'津波予報区',p=Object.entries(tsunamiCoords).find(([k])=>name.includes(k))?.[1]||[35,140];return{id:`tsunami-${when}-${i}-${name}`,kind:'tsunami',place:name,lat:p[0],lon:p[1],countryCode:'JP',time:when,intensity:gradeMap[a.grade]||'津波情報',source:'P2P / 気象庁'}})}
  function usgsEvents(json){return(json.features||[]).map(f=>{const c=f.geometry?.coordinates||[],p=f.properties||{};if(c.length<2)return null;const time=Number(p.time)||Date.now(),raw=p.place||'';return{id:`usgs-${f.id}`,kind:'quake',place:raw.includes('Japan')?`日本付近（${raw.replace(/\s+of\s+/,'の')}）`:`${c[1].toFixed(1)}°, ${c[0].toFixed(1)}°`,lat:Number(c[1]),lon:Number(c[0]),depth:Number(c[2]),mag:Number(p.mag)||0,time,originTime:time,countryCode:/\bJapan\b/i.test(raw)?'JP':'',intensity:Number(p.mag)>=4?'要注目':'',source:'USGS'}}).filter(Boolean)}
  function gdacsEvents(json){return(json.features||json.events||[]).map((f,i)=>{const p=f.properties||f,g=f.geometry||{},c=g.coordinates||[],lat=Number(p.latitude??(Array.isArray(c[0])?c[0][1]:c[1])),lon=Number(p.longitude??(Array.isArray(c[0])?c[0][0]:c[0]));if(!Number.isFinite(lat)||!Number.isFinite(lon))return null;const type=String(p.eventtype||p.eventType||p.type||'').toUpperCase(),time=Date.parse(p.fromdate||p.fromDate||p.eventdate||p.date)||Date.now(),country=String(p.countrycode||p.countryCode||'');return{id:`gdacs-${p.eventid||p.eventId||p.id||i}`,kind:type==='EQ'?'quake':type==='TC'?'storm':'other',hazardType:type,place:p.eventname||p.name||p.country||`${lat.toFixed(1)}°, ${lon.toFixed(1)}°`,lat,lon,countryCode:/^(JP|JPN|JAPAN)$/i.test(country)?'JP':'',time,intensity:p.alertlevel||p.alertLevel||p.severity||'災害情報',source:'GDACS'}}).filter(Boolean)}
  async function request(url){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000);try{const res=await fetch(url,{cache:'no-store',signal:controller.signal});if(!res.ok)throw Error(`${res.status}`);return await res.json()}finally{clearTimeout(timer)}}
  function merge(incoming){const map=new Map(events.map(e=>[String(e.id),e]));for(const item of incoming){const old=map.get(String(item.id));map.set(String(item.id),old?{...old,...item,receivedAt:old.receivedAt||Date.now()}: {...item,receivedAt:Date.now()})}events=[...map.values()].filter(e=>Number(e.time)>Date.now()-7*DAY).sort((a,b)=>Number(b.time)-Number(a.time)).slice(0,700);persist();render()}
  async function refresh(){const button=$('refreshBtn');if(!navigator.onLine){setStatus('オフライン：保存データを表示中',false);toast('ネット接続がありません。保存データを表示しています');return}button.disabled=true;button.textContent='取得中…';setStatus('データを取得中',true);const urls=[['p2p','https://api.p2pquake.net/v2/history?codes=551,556,552&limit=100&offset=0'],['usgs','https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.geojson'],['gdacs',`https://www.gdacs.org/gdacsapi/api/Events/geteventlist/SEARCH?eventlist=EQ;TC;FL;DR;VO;WF&fromdate=${new Date(Date.now()-7*DAY).toISOString().slice(0,10)}&todate=${new Date().toISOString().slice(0,10)}&alertlevel=green;orange;red`]];try{const results=await Promise.allSettled(urls.map(x=>request(x[1]))),batch=[];let ok=0;for(let i=0;i<results.length;i++){const r=results[i];if(r.status!=='fulfilled')continue;ok++;if(i===0){for(const item of r.value){const code=Number(item.code);if(code===551||code===556){const e=eventFromP2P(item);if(e)batch.push(e)}else if(code===552)batch.push(...eventFromTsunami(item))}}else if(i===1)batch.push(...usgsEvents(r.value));else batch.push(...gdacsEvents(r.value))}if(batch.length)merge(batch);else{persist();render()}const stamp=Date.now();await store.set('savedAt',stamp);$('savedAt').textContent=new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(stamp)+' 東京';if(ok)setStatus(`更新完了 · ${ok}/3配信元`,true);else setStatus('取得できません：保存データを表示中',false);toast(ok?`データを更新しました（${batch.length}件を受信）`:'取得できませんでした。保存済みデータを表示します')}catch{setStatus('取得できません：保存データを表示中',false)}finally{button.disabled=false;button.textContent='↻ オンラインで更新'}}
  function exportData(){const data={format:'earth-observe-offline-v1',savedAt:Date.now(),events};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`earth-observe-data-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('イベントデータを書き出しました')}
  function importData(file){if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const obj=JSON.parse(reader.result),arr=Array.isArray(obj)?obj:obj.events;if(!Array.isArray(arr))throw Error('events');const cleaned=arr.filter(e=>e&&e.kind&&Number.isFinite(Number(e.time))&&Number.isFinite(Number(e.lat))&&Number.isFinite(Number(e.lon))).map(e=>({...e,lat:Number(e.lat),lon:Number(e.lon),time:Number(e.time)}));if(!cleaned.length)throw Error('empty');merge(cleaned);setStatus('インポート済みデータを表示中',navigator.onLine);toast(`${cleaned.length}件のイベントを読み込みました`)}catch{toast('このJSONデータは読み込めませんでした')}finally{$('fileInput').value=''}};reader.readAsText(file)}
  function attachCanvas(){const c=$('globe');c.addEventListener('pointerdown',e=>{dragging=true;lastPointer=pointerStart={x:e.clientX,y:e.clientY};c.setPointerCapture(e.pointerId)});c.addEventListener('pointermove',e=>{if(!dragging)return;const dx=e.clientX-lastPointer.x,dy=e.clientY-lastPointer.y;lastPointer={x:e.clientX,y:e.clientY};rotLon+=dx*.009;rotLat=Math.max(-1.45,Math.min(1.45,rotLat+dy*.009));draw()});c.addEventListener('pointerup',e=>{if(!dragging)return;const moved=pointerStart?Math.hypot(e.clientX-pointerStart.x,e.clientY-pointerStart.y):0;dragging=false;pointerStart=null;if(moved<9){const x=e.clientX-c.getBoundingClientRect().left,y=e.clientY-c.getBoundingClientRect().top,rect=c.getBoundingClientRect(),cx=rect.width/2,cy=rect.height/2,R=Math.min(rect.width,rect.height)*.44;let hit=null,distance=18;for(const ev of visible()){const p=projectForHit(Number(ev.lon),Number(ev.lat),cx,cy,R);if(!p||p.z<=0)continue;const d=Math.hypot(p.x-x,p.y-y);if(d<distance){distance=d;hit=ev}}if(hit)selectEvent(hit.id)} });c.addEventListener('pointercancel',()=>{dragging=false;pointerStart=null})}
  function projectForHit(lon,lat,cx,cy,r){const p=lat*Math.PI/180,l=lon*Math.PI/180-rotLon,cp=Math.cos(p),z=Math.sin(p)*Math.cos(rotLat)+cp*Math.cos(l)*Math.sin(rotLat);return{x:cx+r*cp*Math.sin(l),y:cy-r*(Math.sin(p)*Math.cos(rotLat)-cp*Math.cos(l)*Math.sin(rotLat)),z}}
  async function init(){await store.open();events=await store.get('events')||[];const saved=await store.get('savedAt');if(saved)$('savedAt').textContent=new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(saved)+' 東京';$('storageHint').textContent=db?'':' · ブラウザー内保存';try{const res=await fetch('./world-countries-50m.geojson');if(res.ok){const geo=await res.json();countryFeatures=geo.features||[]}}catch{}render();setStatus(navigator.onLine?'保存データを表示中':'オフライン：保存データを表示中',navigator.onLine);tick();setInterval(tick,1000);if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{});addEventListener('online',()=>setStatus('オンライン · 必要時に更新できます',true));addEventListener('offline',()=>setStatus('オフライン：保存データを表示中',false));new ResizeObserver(draw).observe($('globe'));attachCanvas()}
  $('refreshBtn').addEventListener('click',refresh);$('exportBtn').addEventListener('click',exportData);$('importBtn').addEventListener('click',()=>$('fileInput').click());$('fileInput').addEventListener('change',e=>importData(e.target.files?.[0]));$('filters').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;filter=b.dataset.filter;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));render()});$('clearFilter').addEventListener('click',()=>{filter='all';document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter==='all'));render()});
  init();
})();
